version: 2

project_name: fireauth

builds:
  - main: .
    binary: fireauth
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: andrespd99
    name: fireauth

brews:
  - name: fireauth
    directory: Formula
    homepage: "https://github.com/andrespd99/fireauth"
    description: "CLI tool for authenticating against Firebase and managing bearer tokens for REST API testing."
    license: "MIT"
    test: |
      system "#{bin}/fireauth", "--help"
    repository:
      owner: andrespd99
      name: homebrew-fireauth
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@users.noreply.github.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
